/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThothshopRouteImport } from './routes/thothshop'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThothfoodIndexRouteImport } from './routes/thothfood/index'
import { Route as ThothfoodPricingRouteImport } from './routes/thothfood/pricing'
import { Route as ThothfoodHowItWorksRouteImport } from './routes/thothfood/how-it-works'
import { Route as ThothfoodForRestaurantsRouteImport } from './routes/thothfood/for-restaurants'

const ThothshopRoute = ThothshopRouteImport.update({
  id: '/thothshop',
  path: '/thothshop',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThothfoodIndexRoute = ThothfoodIndexRouteImport.update({
  id: '/thothfood/',
  path: '/thothfood/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThothfoodPricingRoute = ThothfoodPricingRouteImport.update({
  id: '/thothfood/pricing',
  path: '/thothfood/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ThothfoodHowItWorksRoute = ThothfoodHowItWorksRouteImport.update({
  id: '/thothfood/how-it-works',
  path: '/thothfood/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ThothfoodForRestaurantsRoute = ThothfoodForRestaurantsRouteImport.update({
  id: '/thothfood/for-restaurants',
  path: '/thothfood/for-restaurants',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/restaurants': typeof RestaurantsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thothshop': typeof ThothshopRoute
  '/thothfood/for-restaurants': typeof ThothfoodForRestaurantsRoute
  '/thothfood/how-it-works': typeof ThothfoodHowItWorksRoute
  '/thothfood/pricing': typeof ThothfoodPricingRoute
  '/thothfood/': typeof ThothfoodIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/restaurants': typeof RestaurantsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thothshop': typeof ThothshopRoute
  '/thothfood/for-restaurants': typeof ThothfoodForRestaurantsRoute
  '/thothfood/how-it-works': typeof ThothfoodHowItWorksRoute
  '/thothfood/pricing': typeof ThothfoodPricingRoute
  '/thothfood': typeof ThothfoodIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/restaurants': typeof RestaurantsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thothshop': typeof ThothshopRoute
  '/thothfood/for-restaurants': typeof ThothfoodForRestaurantsRoute
  '/thothfood/how-it-works': typeof ThothfoodHowItWorksRoute
  '/thothfood/pricing': typeof ThothfoodPricingRoute
  '/thothfood/': typeof ThothfoodIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/products'
    | '/restaurants'
    | '/sitemap.xml'
    | '/terms'
    | '/thothshop'
    | '/thothfood/for-restaurants'
    | '/thothfood/how-it-works'
    | '/thothfood/pricing'
    | '/thothfood/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/products'
    | '/restaurants'
    | '/sitemap.xml'
    | '/terms'
    | '/thothshop'
    | '/thothfood/for-restaurants'
    | '/thothfood/how-it-works'
    | '/thothfood/pricing'
    | '/thothfood'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/products'
    | '/restaurants'
    | '/sitemap.xml'
    | '/terms'
    | '/thothshop'
    | '/thothfood/for-restaurants'
    | '/thothfood/how-it-works'
    | '/thothfood/pricing'
    | '/thothfood/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  RestaurantsRoute: typeof RestaurantsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ThothshopRoute: typeof ThothshopRoute
  ThothfoodForRestaurantsRoute: typeof ThothfoodForRestaurantsRoute
  ThothfoodHowItWorksRoute: typeof ThothfoodHowItWorksRoute
  ThothfoodPricingRoute: typeof ThothfoodPricingRoute
  ThothfoodIndexRoute: typeof ThothfoodIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thothshop': {
      id: '/thothshop'
      path: '/thothshop'
      fullPath: '/thothshop'
      preLoaderRoute: typeof ThothshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thothfood/': {
      id: '/thothfood/'
      path: '/thothfood'
      fullPath: '/thothfood/'
      preLoaderRoute: typeof ThothfoodIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thothfood/pricing': {
      id: '/thothfood/pricing'
      path: '/thothfood/pricing'
      fullPath: '/thothfood/pricing'
      preLoaderRoute: typeof ThothfoodPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thothfood/how-it-works': {
      id: '/thothfood/how-it-works'
      path: '/thothfood/how-it-works'
      fullPath: '/thothfood/how-it-works'
      preLoaderRoute: typeof ThothfoodHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thothfood/for-restaurants': {
      id: '/thothfood/for-restaurants'
      path: '/thothfood/for-restaurants'
      fullPath: '/thothfood/for-restaurants'
      preLoaderRoute: typeof ThothfoodForRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  RestaurantsRoute: RestaurantsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ThothshopRoute: ThothshopRoute,
  ThothfoodForRestaurantsRoute: ThothfoodForRestaurantsRoute,
  ThothfoodHowItWorksRoute: ThothfoodHowItWorksRoute,
  ThothfoodPricingRoute: ThothfoodPricingRoute,
  ThothfoodIndexRoute: ThothfoodIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
